### ISSUE TITLE
Team Calendar Not Accessible

### ISSUE THREAD

**Issue by joshuamorton915** [microsoft/vsts-team-calendar#372]
I have one user who is attempting to access the team calendar for a project. When clicking on Boards - Calendar, the user is prompted with a Windows Security prompt that states: Authorization required by (site). 

It prompts for username and password. If the user enters their network credentials, they are just prompted by the same popup for credentials again. I do not find any permission variances when compared to other users assigned to this project who can access the team calendar successfully. What am I missing?

We are running Azure DevOps Server 2020 Update 1.1 and the team calendar is created by Microsoft DevLabs.

**Comment by djcornutt** [comment]
Just upgraded a customer from 2020 to 2022 and now his Team Calendar extension prompts users for authentication and it never completes. Unistalled/reinstalled it to no avail.

**Comment by djcornutt** [comment]
Does this help?
Content?bundle=vss-bundle-basejs-vPKQEdNKMUBnHN-IzfQoxgb6hNY-SZb5VFy_iJyFZJi4=:20 JQMIGRATE: Migrate is installed, version 3.4.0
jquery-migrate-3.4.0.min.js:2 JQMIGRATE: jQuery 3.0.0+ REQUIRED
jquery-migrate-3.4.0.min.js:2 JQMIGRATE: Migrate is installed, version 3.4.0
jquery-migrate-3.4.0.min.js:2 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'apply')
    at e.<computed> [as unique] (jquery-migrate-3.4.0.min.js:2:1394)
    at e.<computed>.add (jquery.js:2945:11)
    at c (fullcalendar.min.js:6:1130)
    at e.constructor.computeScrollerHeight (fullcalendar.min.js:10:30853)
    at e.constructor.updateSize (fullcalendar.min.js:10:30525)
    at constructor.updateViewSize (fullcalendar.min.js:9:10012)
    at e.constructor.onRenderQueueStop (fullcalendar.min.js:8:16222)
    at constructor.n (fullcalendar.min.js:6:19787)
    at constructor.dispatch (jquery.js:4435:9)
    at r.handle (jquery.js:4121:28)
e.<computed> @ jquery-migrate-3.4.0.min.js:2
add @ jquery.js:2945
c @ fullcalendar.min.js:6
computeScrollerHeight @ fullcalendar.min.js:10
updateSize @ fullcalendar.min.js:10
updateViewSize @ fullcalendar.min.js:9
onRenderQueueStop @ fullcalendar.min.js:8
n @ fullcalendar.min.js:6
dispatch @ jquery.js:4435
r.handle @ jquery.js:4121
trigger @ jquery.js:4350
triggerHandler @ jquery.js:4907
trigger @ fullcalendar.min.js:6
runRemaining @ fullcalendar.min.js:6
tryStart @ fullcalendar.min.js:6
resume @ fullcalendar.min.js:6
stopBatchRender @ fullcalendar.min.js:8
n @ fullcalendar.min.js:6
dispatch @ jquery.js:4435
r.handle @ jquery.js:4121
trigger @ jquery.js:4350
triggerHandler @ jquery.js:4907
trigger @ fullcalendar.min.js:6
setProps @ fullcalendar.min.js:6
set @ fullcalendar.min.js:6
setDate @ fullcalendar.min.js:8
renderView @ fullcalendar.min.js:9
initialRender @ fullcalendar.min.js:9
render @ fullcalendar.min.js:9
(anonymous) @ fullcalendar.min.js:6
each @ jquery.js:374
each @ jquery.js:139
t.fn.fullCalendar @ fullcalendar.min.js:6
Calendar.initialize @ main.js:20769
n._attemptInitialize @ Controls.js:2
t.createIn @ Controls.js:2
t.createIn @ Controls.js:2
t.create @ Controls.js:2
g @ Controls.js:2
CalendarView.initialize @ main.js:20094
n._attemptInitialize @ Controls.js:2
t.createIn @ Controls.js:2
t.createIn @ Controls.js:2
t.create @ Controls.js:2
g @ Controls.js:2
CalendarComponent.enhanceControls @ main.js:19947
ref @ main.js:20060
r @ react.15.3.js:15
a.attachRefs @ react.15.3.js:15
r @ react.15.3.js:15
notifyAll @ react.15.3.js:12
close @ react.15.3.js:15
closeAll @ react.15.3.js:16
perform @ react.15.3.js:16
perform @ react.15.3.js:16
perform @ react.15.3.js:15
P @ react.15.3.js:15
closeAll @ react.15.3.js:16
perform @ react.15.3.js:16
batchedUpdates @ react.15.3.js:14
u @ react.15.3.js:15
r @ react.15.3.js:15
enqueueForceUpdate @ react.15.3.js:15
r.forceUpdate @ react.15.3.js:13
(anonymous) @ main.js:19812
setTimeout (async)
(anonymous) @ main.js:19811
step @ main.js:179
(anonymous) @ main.js:160
fulfilled @ main.js:150
Promise.then (async)
step @ main.js:152
fulfilled @ main.js:150
Promise.then (async)
step @ main.js:152
fulfilled @ main.js:150
Promise.then (async)
step @ main.js:152
fulfilled @ main.js:150
Promise.then (async)
step @ main.js:152
fulfilled @ main.js:150
Promise.then (async)
step @ main.js:152
fulfilled @ main.js:150
Promise.then (async)
step @ main.js:152
(anonymous) @ main.js:153
__awaiter @ main.js:149
CalendarStateManagerComponent.initialize @ main.js:19776
CalendarStateManagerComponent @ main.js:19772
_constructComponentWithoutOwner @ react.15.3.js:13
_constructComponent @ react.15.3.js:13
mountComponent @ react.15.3.js:13
mountComponent @ react.15.3.js:15
performInitialMount @ react.15.3.js:13
mountComponent @ react.15.3.js:13
mountComponent @ react.15.3.js:15
a @ react.15.3.js:14
perform @ react.15.3.js:16
s @ react.15.3.js:14
perform @ react.15.3.js:16
batchedUpdates @ react.15.3.js:14
i @ react.15.3.js:15
_renderNewRootComponent @ react.15.3.js:14
_renderSubtreeIntoContainer @ react.15.3.js:14
render @ react.15.3.js:14
(anonymous) @ main.js:19679
j @ jquery.js:3099
add @ jquery.js:3145
n.fn.ready @ jquery.js:3378
n.fn.init @ jquery.js:2821
(anonymous) @ jquery-migrate-3.4.0.min.js:2
e.<computed> @ jquery-migrate-3.4.0.min.js:2
n @ jquery.js:76
(anonymous) @ main.js:19678
(anonymous) @ main.js:19681
__webpack_require__ @ main.js:20
(anonymous) @ main.js:63
(anonymous) @ main.js:66
execCb @ require.min.js:6
check @ require.min.js:6
(anonymous) @ require.min.js:6
(anonymous) @ require.min.js:6
(anonymous) @ require.min.js:6
u @ require.min.js:6
emit @ require.min.js:6
check @ require.min.js:6
(anonymous) @ require.min.js:6
(anonymous) @ require.min.js:6
(anonymous) @ require.min.js:6
u @ require.min.js:6
emit @ require.min.js:6
check @ require.min.js:6
(anonymous) @ require.min.js:6
(anonymous) @ require.min.js:6
(anonymous) @ require.min.js:6
u @ require.min.js:6
emit @ require.min.js:6
check @ require.min.js:6
(anonymous) @ require.min.js:6
(anonymous) @ require.min.js:6
(anonymous) @ require.min.js:6
u @ require.min.js:6
emit @ require.min.js:6
check @ require.min.js:6
(anonymous) @ require.min.js:6
(anonymous) @ require.min.js:6
(anonymous) @ require.min.js:6
u @ require.min.js:6
emit @ require.min.js:6
check @ require.min.js:6
(anonymous) @ require.min.js:6
(anonymous) @ require.min.js:6
(anonymous) @ require.min.js:6
u @ require.min.js:6
emit @ require.min.js:6
check @ require.min.js:6
enable @ require.min.js:6
init @ require.min.js:6
fi @ require.min.js:6
completeLoad @ require.min.js:6
onScriptLoad @ require.min.js:6
load (async)
t.load @ require.min.js:6
load @ require.min.js:6
load @ require.min.js:6
fetch @ require.min.js:6
check @ require.min.js:6
enable @ require.min.js:6
enable @ require.min.js:6
(anonymous) @ require.min.js:6
(anonymous) @ require.min.js:6
u @ require.min.js:6
enable @ require.min.js:6
init @ require.min.js:6
fi @ require.min.js:6
completeLoad @ require.min.js:6
onScriptLoad @ require.min.js:6
load (async)
t.load @ require.min.js:6
load @ require.min.js:6
load @ require.min.js:6
fetch @ require.min.js:6
check @ require.min.js:6
enable @ require.min.js:6
enable @ require.min.js:6
(anonymous) @ require.min.js:6
(anonymous) @ require.min.js:6
u @ require.min.js:6
enable @ require.min.js:6
init @ require.min.js:6
fi @ require.min.js:6
completeLoad @ require.min.js:6
onScriptLoad @ require.min.js:6
load (async)
t.load @ require.min.js:6
load @ require.min.js:6
load @ require.min.js:6
fetch @ require.min.js:6
check @ require.min.js:6
enable @ require.min.js:6
enable @ require.min.js:6
(anonymous) @ require.min.js:6
(anonymous) @ require.min.js:6
u @ require.min.js:6
enable @ require.min.js:6
init @ require.min.js:6
fi @ require.min.js:6
completeLoad @ require.min.js:6
onScriptLoad @ require.min.js:6
load (async)
t.load @ require.min.js:6
load @ require.min.js:6
load @ require.min.js:6
fetch @ require.min.js:6
check @ require.min.js:6
enable @ require.min.js:6
enable @ require.min.js:6
(anonymous) @ require.min.js:6
(anonymous) @ require.min.js:6
u @ require.min.js:6
enable @ require.min.js:6
init @ require.min.js:6
fi @ require.min.js:6
completeLoad @ require.min.js:6
onScriptLoad @ require.min.js:6
load (async)
t.load @ require.min.js:6
load @ require.min.js:6
load @ require.min.js:6
fetch @ require.min.js:6
check @ require.min.js:6
enable @ require.min.js:6
enable @ require.min.js:6
(anonymous) @ require.min.js:6
(anonymous) @ require.min.js:6
u @ require.min.js:6
enable @ require.min.js:6
init @ require.min.js:6
(anonymous) @ require.min.js:6
setTimeout (async)
t.nextTick @ require.min.js:6
f @ require.min.js:6
requirejs @ require.min.js:6
(anonymous) @ calendar.html:31
(anonymous) @ VSS.SDK.js:1396
triggerReady @ VSS.SDK.js:1395
(anonymous) @ VSS.SDK.js:1279
addScriptElements @ VSS.SDK.js:1352
addScriptElements @ VSS.SDK.js:1371
(anonymous) @ VSS.SDK.js:1361
load (async)
addScriptElements @ VSS.SDK.js:1360
(anonymous) @ VSS.SDK.js:1361
load (async)
addScriptElements @ VSS.SDK.js:1360
(anonymous) @ VSS.SDK.js:1361
load (async)
addScriptElements @ VSS.SDK.js:1360
(anonymous) @ VSS.SDK.js:1361
load (async)
addScriptElements @ VSS.SDK.js:1360
(anonymous) @ VSS.SDK.js:1361
load (async)
addScriptElements @ VSS.SDK.js:1360
(anonymous) @ VSS.SDK.js:1361
load (async)
addScriptElements @ VSS.SDK.js:1360
setupAmdLoader @ VSS.SDK.js:1277
(anonymous) @ VSS.SDK.js:888
XdmDeferred._wrapCallback @ VSS.SDK.js:63
(anonymous) @ VSS.SDK.js:38
(anonymous) @ VSS.SDK.js:93
setTimeout (async)
XdmDeferred._resolve @ VSS.SDK.js:91
XdmDeferred.resolve @ VSS.SDK.js:19
XDMChannel.onMessage @ VSS.SDK.js:337
XDMChannelManager._handleMessageReceived @ VSS.SDK.js:637
(anonymous) @ VSS.SDK.js:656
postMessage (async)
_sendRpcMessage @ ms.vss-web.ext-content.es6.IhPvtQ.min.js:1
_success @ ms.vss-web.ext-content.es6.IhPvtQ.min.js:1
(anonymous) @ ms.vss-web.ext-content.es6.IhPvtQ.min.js:1
Promise.then (async)
invokeMethod @ ms.vss-web.ext-content.es6.IhPvtQ.min.js:1
invokeMethodByName @ ms.vss-web.ext-content.es6.IhPvtQ.min.js:1
onMessage @ ms.vss-web.ext-content.es6.IhPvtQ.min.js:1
_handleMessageReceived @ ms.vss-web.ext-content.es6.IhPvtQ.min.js:1
postMessage (async)
XDMChannel._sendRpcMessage @ VSS.SDK.js:395
XDMChannel.invokeRemoteMethod @ VSS.SDK.js:233
(anonymous) @ VSS.SDK.js:850
setTimeout (async)
init @ VSS.SDK.js:844
(anonymous) @ calendar.html:20
jquery-migrate-3.4.0.min.js:2 
        
       Uncaught TypeError: s.event.addProp is not a function
    at Object.<anonymous> (jquery-migrate-3.4.0.min.js:2:9366)
    at e.<computed> [as fix] (jquery-migrate-3.4.0.min.js:2:1394)
    at HTMLDocument.dispatch (jquery.js:4399:24)
    at r.handle (jquery.js:4121:28)
(anonymous) @ jquery-migrate-3.4.0.min.js:2
e.<computed> @ jquery-migrate-3.4.0.min.js:2
dispatch @ jquery.js:4399
r.handle @ jquery.js:4121

**Comment by FireSnakie** [comment]
Hi there

> Just upgraded a customer from 2020 to 2022 and now his Team Calendar extension prompts users for authentication and it never completes. Unistalled/reinstalled it to no avail.

We have exactly the same issue after upgrading to 2022. Uninstall/reinstall did not resolve the issue either.

**Comment by djcornutt** [comment]
The best answer I have gotten is that 2022 is still Release Candidate 1 (RC1) so lots of stuff is still broken. RC2 should come out this week which may fix this issue. If not, the  RTW (final) release might have a fix as well. Don't use RCs on production systems--testing only.

**Comment by djcornutt** [comment]
RC2 came out Tuesday, Oct 25th, and it resolves the Calendar extension issue.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
